# permissions for end users to edit autosvcigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: autosvcigs-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder-autosvcigs
    app.kubernetes.io/part-of: kubebuilder-autosvcigs
    app.kubernetes.io/managed-by: kustomize
  name: autosvcigs-editor-role
rules:
- apiGroups:
  - auto.rock.com
  resources:
  - autosvcigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auto.rock.com
  resources:
  - autosvcigs/status
  verbs:
  - get
